repos:
  # Basic checks (trailing whitespace)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest version or specify as needed
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml


  # Ruff linter with specific checks and bugbear, isort, ruff, and pyupgrade plugins
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1  # Use the latest version or specify as needed
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: [--fix, --show-fixes]  # Automatically format files
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies:
        - nox
        - types-Flask  # Type stubs for Flask
        - types-PyYAML  # Type stubs for PyYAML
        - pandas-stubs  # Type stubs for pandas
        - numpy  # Type stubs for numpy
        exclude: ^tests/